In [11]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.activations import linear, relu, sigmoid
import numpy as np
import pandas
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.optimizers.legacy import Adam
from tensorflow.keras.regularizers import L2
from xgboost import XGBClassifier, XGBRegressor
from tensorflow.keras.losses import MeanSquaredError
tf.random.set_seed(1048596)
seed()

In [ ]:
data_train = pandas.read_csv("adult-fnlwgt-train.csv").to_numpy()
# print(data_train_2)

scaler = StandardScaler()

X_train = data_train[:,1:-1]
y_train = data_train[:,0]
# y_train = np.reshape(y_train,(-1,1))
print(X_train)

X_train = scaler.fit_transform(X_train)
# y_train = (y_train)
print(X_train)
print("\n\n And this is y_train")
print(y_train)

data_test = pandas.read_csv("adult-fnlwgt-test.csv").to_numpy()

X_test = scaler.transform(data_test[:,1:-1])
y_test = data_test[:,0]
# y_test = np.reshape(y_test,(-1,1))
# y_test = scaler.transform(y_test)

model = Sequential([
    Dense(units = 256, activation = "relu", kernel_regularizer = L2(0.01)),
    Dense(units = 128, activation = "relu", kernel_regularizer = L2(0.01)),
    Dense(units = 64, activation = "relu", kernel_regularizer = L2(0.01)),
    Dense(units = 1, activation = "relu")
])

model.compile(optimizer=Adam(),loss=MeanSquaredError())

model.fit(X_train,y_train,epochs=30)


[[   38     9     0     0]
 [   18    10     0     0]
 [   63    15  3103     0]
 ...
 [   22    10     0     0]
 [   27    12     0     0]
 [   52     9 15024     0]]
[[-0.05166288 -0.42214933 -0.14583034 -0.21728043]
 [-1.50921398 -0.03216345 -0.14583034 -0.21728043]
 [ 1.77027599  1.91776592  0.26576014 -0.21728043]
 ...
 [-1.21770376 -0.03216345 -0.14583034 -0.21728043]
 [-0.85331599  0.7478083  -0.14583034 -0.21728043]
 [ 0.96862288 -0.42214933  1.84699447 -0.21728043]]


 And this is y_train
[ 89814 103497 104626 ... 310152 257302 287927]
Epoch 1/30
   9/1145 [..............................] - ETA: 7s - loss: 51545329664.0000  

2023-01-04 14:21:04.664421: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


1145/1145 [==============================] - 8s 7ms/step - loss: 18927927296.0000
Epoch 2/30
1145/1145 [==============================] - 9s 7ms/step - loss: 11208261632.0000
Epoch 3/30
1145/1145 [==============================] - 7s 6ms/step - loss: 11136803840.0000
Epoch 4/30
1145/1145 [==============================] - 7s 6ms/step - loss: 11122014208.0000
Epoch 5/30
1145/1145 [==============================] - 7s 6ms/step - loss: 11108233216.0000
Epoch 6/30
1145/1145 [==============================] - 7s 6ms/step - loss: 11107624960.0000
Epoch 7/30
 981/1145 [========================>.....] - ETA: 0s - loss: 11062247424.0000

In [8]:
# Use decision trees to predict marital status
data_train = pandas.read_csv("adult-one-hot-train.csv").to_numpy()
# print(data_train_2)

X_train_2 = data_train[:,1:-1]
y_train_2 = data_train[:,0]

data_test = pandas.read_csv("adult-one-hot-test.csv").to_numpy()

X_test_2 = data_test[:,1:-1]
y_test_2 = data_test[:,0]

## Fit model
dec_tree = XGBClassifier()
dec_tree.fit(X_train_2,y_train_2)

## Predict on training dataset
predictions_train_2 = dec_tree.predict(X_train_2)
#predictions_train = #np.where(probabilities_train >= 0.5, 1, 0)

misclassifications_train_2 = 0

for i in range(len(predictions_train_2)):
    if (predictions_train_2[i] == y_train_2[i]):
        misclassifications_train_2 += 1
        
print("train ratio of correct")
print(misclassifications_train_2/len(predictions_train_2))

##########

predictions_test_2 = dec_tree.predict(X_test_2)
# predictions_test = np.where(probabilities_test >= 0.5, 1, 0)

misclassifications_test_2 = 0

for i in range(len(predictions_test_2)):
    if (predictions_test_2[i] == y_test_2[i]):
        misclassifications_test_2 += 1

print("test ratio of correct")
print(misclassifications_test_2/len(predictions_test_2))


train ratio of correct
0.7689115776255084
test ratio of correct
0.7610351322578004


In [9]:
# Use decision trees to predict income
data_train = pandas.read_csv("adult-one-hot-train-income.csv").to_numpy()
# print(data_train_2)

X_train_2 = data_train[:,1:-1]
y_train_2 = data_train[:,0]

data_test = pandas.read_csv("adult-one-hot-test-income.csv").to_numpy()

X_test_2 = data_test[:,1:-1]
y_test_2 = data_test[:,0]

## Fit model
dec_tree = XGBRegressor()
dec_tree.fit(X_train_2,y_train_2)

## Predict on training dataset
predictions_train_2 = dec_tree.predict(X_train_2)
#predictions_train = #np.where(probabilities_train >= 0.5, 1, 0)

MSE = 0

for i in range(len(predictions_train_2)):
    MSE += (predictions_train_2[i] - y_train_2[i])**2
MSE = MSE/len(predictions_train_2)
print("train MSE")
print(MSE)

##########

predictions_test_2 = dec_tree.predict(X_test_2)
# predictions_test = np.where(probabilities_test >= 0.5, 1, 0)

MSE = 0

for i in range(len(predictions_test_2)):
    MSE += (predictions_test_2[i] - y_test_2[i])**2
MSE = MSE/len(predictions_test_2)

print("test MSE")
print(MSE)


train MSE
10023217712.796402
test MSE
11038538430.688465
